server:
  servlet:
    context-path: /store

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bookstore
    username: root
    password: Tea0816@
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      data-source-properties:
        integratedSecurity: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
